all:
	rustup run nightly-x86_64-unknown-linux-gnu cargo run -- -L ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/ -L ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/ ~/.test/basic/basic.rs
